modLoader = "javafml"
# The loader version doesn't matter. Modify the NeoForge and/or Minecraft version ranges instead.
loaderVersion = "[0,)"
issueTrackerURL = "https://github.com/SzJu/Create_Steamy/issues"
license = "Read attached LICENSE.md"

[[mods]]
modId = "create_steamy"
version = "1.0"
displayName = "Create Steamy"
displayURL = ""
updateJSONURL = ""
authors = "simibubi"
description = '''Technology that empowers the player.'''

[[mixins]]
config = "create_steamy.mixins.json"

[[dependencies."create_steamy"]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.219,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."create_steamy"]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"
